//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDonHang
    {
        public int MaDH { get; set; }
        public int MaSP { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập số lượng")]
        [Range(0, 400, ErrorMessage = "Số lượng phải là số có giá trị từ 0 - 400")]
        public Nullable<int> SoLuong { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập đơn giá")]
        [Range(1000, 400000000, ErrorMessage = "Giá phải là số thấp nhất là 1000")]
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> Tongcong { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
