//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }

        public int MaDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        [Display(Name = "Tổng tiền")]
        public Nullable<decimal> TongTien { get; set; }
        [Display(Name = "Ngày đặt")]
        public Nullable<System.DateTime> NgayDat { get; set; }
        [Display(Name = "Ngày giao")]
        public Nullable<System.DateTime> NgayGiao { get; set; }
        [Display(Name = "Lưu ý")]

        public string LuuY { get; set; }
        [Display(Name = "Tình trạng")]
        public string TinhTrang { get; set; }
        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Không được phép để trống")]
        public string DiaChi { get; set; }
        [Display(Name = "Số điện thoại")]
        [Required(ErrorMessage = "Không được phép để trống"), StringLength(11, MinimumLength = 10, ErrorMessage = "Số điện thoại phải có ít nhất 10 số")]
        [RegularExpression("^0[0-9]{9,10}$", ErrorMessage = "Số điện thoại không hợp lệ")]
        public string Sdt { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual User User { get; set; }
    }
}
