//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }

        [Display(Name = "Mã sản phẩm")]
        public int MaSP { get; set; }
        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "Không được phép để trống"), StringLength(49, MinimumLength = 1, ErrorMessage = "Phải có ít nhất 1-49 kí tự")]
        public string TenSP { get; set; }
        [Display(Name = "Giá bán")]
        [Required(ErrorMessage = "Bạn chưa nhập giá sản phẩm")]
        [Range(1000, 400000000, ErrorMessage = "Giá phải là số thấp nhất là 1000")]
        public Nullable<decimal> GiaBan { get; set; }
        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "Không được phép để trống")]
        public string MoTa { get; set; }
        [Display(Name = "Hình ảnh")]
        [Required(ErrorMessage = "Không được phép để trống")]
        public string HinhAnh { get; set; }
        [Display(Name = "Ngày cập nhật")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [Display(Name = "Số lượng còn lại")]
        [Range(0, 400, ErrorMessage = "Số lượng còn lại phải từ 0-400")]
        public Nullable<int> SoLuongCon { get; set; }
        [Display(Name = "Mã loại")]
        public Nullable<int> MaLoai { get; set; }
        [Display(Name = "Mã nhà cung cấp")]

        public Nullable<int> NhaCungCap { get; set; }
        [Display(Name = "Hạng dùng")]
        public Nullable<System.DateTime> HanSuDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual LoaiSp LoaiSp { get; set; }
        public virtual NhaCungCap NhaCungCap1 { get; set; }
    }
}
